---
  - name: Ansible test
    hosts: localhost
    tasks:
      - name: launching AWS instance using Ansible
        ec2:
          aws_access_key: xxxxxxxxxxxxxxxxx
          aws_secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
          key_name: webserver
          instance_type: t2.micro
          image: ami-08f3d892de259504d
          region: us-east-1
          wait: yes
          group: default
          count: 1
          vpc_subnet_id: subnet-cde2dbe3
          assign_public_ip: yes
