---
  - hosts: web
    tasks:
# Installing all security updates

      - name: install security updates
        yum:
          name: '*'
          security: yes
          state: latest
# updating kernel package
      - name: updating kernel.
        yum:
          name: kernel*
          state: latest
        register: task_result
# reboot if kernel successfully updated
      - name: Reboot immediately if there was a change.
        shell: "sleep 5 && reboot"
        async: 1
        poll: 0
        when: task_result is changed

      - name: Wait for the reboot to complete if there was a change.
        wait_for_connection:
          connect_timeout: 20
          sleep: 5
          delay: 5
          timeout: 300
        when: task_result is changed
      - name: Checking all kernel package
        shell:  for PACKAGE in $(rpm -qa | grep kernel); do echo "$PACKAGE was installed on  $(date -d @$(rpm -q --qf "%{INSTALLTIME}\n" $PACKAGE))"; done
        register: result
      - name: Listing all kernel packages
        debug: var=result
